Update README with release info & badges
Project-MONAI/monai-deploy-messaging pull request #8
Opened 2022-04-08 21:17 UTC by mocsharp

2022-04-19 16:23 UTC, dbericat requested changes
Couple of copy paste storage vs messaging. Please review

2022-04-19 16:23 UTC, dbericat commented on README.md
> +Development builds are made from all branches except the `main` branch and the `release/*` branches. The NuGet packages are released to [GitHub](https://github.com/Project-MONAI/monai-deploy-storage/
Messaging. Not storage?

2022-04-19 16:23 UTC, dbericat commented on README.md
> +The MONAI Deploy Storage library is released in NuGet format, which is available on both [NuGet.Org](https://www.nuget.org/packages/Monai.Deploy.Storage/) and [GitHub](https://github.com/Project-MONA
Messaging, not storage

2022-04-19 16:31 UTC, mocsharp commented on README.md
> +Development builds are made from all branches except the `main` branch and the `release/*` branches. The NuGet packages are released to [GitHub](https://github.com/Project-MONAI/monai-deploy-storage/
Good catch; fixed

2022-04-19 16:31 UTC, mocsharp commented on README.md
> +The MONAI Deploy Storage library is released in NuGet format, which is available on both [NuGet.Org](https://www.nuget.org/packages/Monai.Deploy.Storage/) and [GitHub](https://github.com/Project-MONA
Good catch; fixed

2022-04-19 16:36 UTC, dbericat requested changes
Minor grammar

2022-04-19 16:36 UTC, dbericat commented on README.md
> +For guidance on contributing MONAI Deploy Messaging, see the [contributing guidelines](https://github.com/Project-MONAI/monai-deploy/blob/main/CONTRIBUTING.md).
contributing TO?

2022-04-20 20:39 UTC, mocsharp commented on README.md
> +For guidance on contributing MONAI Deploy Messaging, see the [contributing guidelines](https://github.com/Project-MONAI/monai-deploy/blob/main/CONTRIBUTING.md).
Fixed

2022-05-04 00:33 UTC, dbericat approved these changes
LGTM

2022-05-04 01:53 UTC, merged